---
- name: install ntp related packages
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ required_packages }}"

- name: config chrony
  import_tasks: config_chrony.yml

- name: start ntp related services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ required_services }}"