---
- name: install db related packages
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ required_packages }}"

- name: config mariadb
  template:
    src: openstack.j2
    dest: /etc/my.cnf.d/openstack.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mariadb

- name: start db related services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ required_services }}"

- name: copy file to config mysql secure
  copy: src=mysql_secure_config dest=/tmp/mysql_secure_config

- name: run script mysql_secure_installation
  shell: mysql_secure_installation < /tmp/mysql_secure_config
  notify:
    - delete mysql_secure_config

- name: create openstack related databases and users
  import_tasks: openstack_config.yml