---
- name: create database glance
  mysql_db:
    encoding: utf8
    name: "{{ glance_db }}"
    state: present

- name: create user glance for database glance
  mysql_user:
    name: "{{ glance_db_user }}"
    password: "{{ glance_db_user_passwd }}"
    priv: "{{ glance_db }}.*:ALL"
    append_privs: yes
    host: "{{ item }}"
    state: present
  with_items: ["localhost", "%"]