---
- name: create database neutron
  mysql_db:
    encoding: utf8
    name: "{{ neutron_db }}"
    state: present

- name: create user neutron for database neutron
  mysql_user:
    name: "{{ neutron_db_user }}"
    password: "{{ neutron_db_user_passwd }}"
    priv: "{{ neutron_db }}.*:ALL"
    append_privs: yes
    host: "{{ item }}"
    state: present
  with_items: ["localhost", "%"]