---
- name: Be sure service project is created
  os_project:
    name: service
    description: Service Project
    domain: default
    region_name: "{{ region_name }}"
    enabled: True
    state: present
    wait: yes

- name: Create the cinder user
  os_user:
    name: cinder
    password: CINDER_PASS
    domain: default
    region_name: "{{ region_name }}"
    enabled: True
    state: present
    wait: yes

- name: Add the admin role to the cinder user and service project
  os_user_role:
    user: cinder
    project: service
    role: admin
    region_name: "{{ region_name }}"
    state: present
    wait: yes

- name: Create the cinderv2 service entity
  os_keystone_service:
    name: cinderv2
    service_type: volumev2
    description: OpenStack Block Storage
    region_name: "{{ region_name }}"
    enabled: True
    state: present

- name: Create the cinderv3 service entity
  os_keystone_service:
    name: cinderv3
    service_type: volumev3
    description: OpenStack Block Storage
    region_name: "{{ region_name }}"
    enabled: True
    state: present

- name: Create the Block Storage service API endpoints
  shell: "{{ item }}"
  with_items:
    - openstack endpoint create --region {{ region_name }} volumev2 public http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v2/%\(project_id\)s
    - openstack endpoint create --region {{ region_name }} volumev2 internal http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v2/%\(project_id\)s
    - openstack endpoint create --region {{ region_name }} volumev2 admin http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v2/%\(project_id\)s
    - openstack endpoint create --region {{ region_name }} volumev3 public http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v3/%\(project_id\)s
    - openstack endpoint create --region {{ region_name }} volumev3 internal http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v3/%\(project_id\)s
    - openstack endpoint create --region {{ region_name }} volumev3 admin http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v3/%\(project_id\)s
  when: ansible_version['full'] | version_compare('2.5', '<')

# - name: Create the volumev2 service API public endpoint
#   os_keystone_endpoint:
#     service: cinder
#     interfdace: public
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v2/%\(project_id\)s
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the volumev2 service API internal endpoint
#   os_keystone_endpoint:
#     service: cinder
#     interfdace: internal
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v2/%\(project_id\)s
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the volumev3 service API admin endpoint
#   os_keystone_endpoint:
#     service: cinder
#     interfdace: admin
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v2/%\(project_id\)s
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the volumev3 service API public endpoint
#   os_keystone_endpoint:
#     service: cinder
#     interfdace: public
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v3/%\(project_id\)s
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the volumev3 service API internal endpoint
#   os_keystone_endpoint:
#     service: cinder
#     interfdace: internal
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v3/%\(project_id\)s
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the volumev3 service API admin endpoint
#   os_keystone_endpoint:
#     service: cinderv3
#     interfdace: admin
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8776/v3/%\(project_id\)s
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')