---
- name: Be sure service project is created
  os_project:
    name: service
    description: Service Project
    domain: default
    region_name: "{{ region_name }}"
    enabled: True
    state: present
    wait: yes

- name: Create the neutron user
  os_user:
    name: neutron
    password: neutron_PASS
    domain: default
    region_name: "{{ region_name }}"
    enabled: True
    state: present
    wait: yes

- name: Add the admin role to the neutron user
  os_user_role:
    user: neutron
    project: service
    role: admin
    region_name: "{{ region_name }}"
    state: present
    wait: yes

- name: Create the neutron service entity
  os_keystone_service:
    name: neutron
    service_type: network
    description: OpenStack Networking
    region_name: "{{ region_name }}"
    enabled: True
    state: present

- name: Create the Networking service API endpoints
  shell: "{{ item }}"
  with_items:
    - openstack endpoint create --region {{ region_name }} network public http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:9696
    - openstack endpoint create --region {{ region_name }} network internal http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:9696
    - openstack endpoint create --region {{ region_name }} network admin http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:9696
  when: ansible_version['full'] | version_compare('2.5', '<')

# - name: Create the Networking service API public endpoint
#   os_keystone_endpoint:
#     service: neutron
#     interfdace: public
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:9696
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the Networking service API internal endpoint
#   os_keystone_endpoint:
#     service: neutron
#     interfdace: internal
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:9696
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the Networking service API admin endpoint
#   os_keystone_endpoint:
#     service: neutron
#     interfdace: admin
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:9696
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')