---
- name: Be sure service project is created
  os_project:
    name: service
    description: Service Project
    domain: default
    region_name: "{{ region_name }}"
    enabled: True
    state: present
    wait: yes

- name: Create the nova user
  os_user:
    name: nova
    password: NOVA_PASS
    domain: default
    region_name: "{{ region_name }}"
    enabled: True
    state: present
    wait: yes

- name: Add the admin role to the nova user
  os_user_role:
    user: nova
    project: service
    role: admin
    region_name: "{{ region_name }}"
    state: present
    wait: yes

- name: Create the nova service entity
  os_keystone_service:
    name: nova
    service_type: compute
    description: OpenStack Compute
    region_name: "{{ region_name }}"
    enabled: True
    state: present

- name: Create the Compute API service endpoints
  shell: "{{ item }}"
  with_items:
    - openstack endpoint list --service nova --column ID --format value | while read id; do openstack endpoint delete ${id}; done
    - openstack endpoint create --region {{ region_name }} compute public http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8774/v2.1
    - openstack endpoint create --region {{ region_name }} compute internal http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8774/v2.1
    - openstack endpoint create --region {{ region_name }} compute admin http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8774/v2.1
  when: ansible_version['full'] | version_compare('2.5', '<')

# - name: Create the Compute API service public endpoint
#   os_keystone_endpoint:
#     service: nova
#     interfdace: public
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8774/v2.1
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the Compute API service internal endpoint
#   os_keystone_endpoint:
#     service: nova
#     interfdace: internal
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8774/v2.1
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')

# - name: Create the Compute API service admin endpoint
#   os_keystone_endpoint:
#     service: nova
#     interfdace: admin
#     url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8774/v2.1
#     region: "{{ region_name }}"
#     enabled: True
#     state: present
#   when: ansible_version['full'] | version_compare('2.5', '>=')