---
base_packages:
  - python-openstackclient
  - openstack-selinux
  - MySQL-python
  - apr
  - apr-util
  - mailcap
  - python-shade
  - python-httplib2
  - python-jmespath

keystone_packages:
  - openstack-keystone
  - httpd
  - mod_wsgi

db_host: "{{ groups['db'][0] }}"
keystone_db: keystone
keystone_db_user: keystone
keystone_db_user_passwd: KEYSTONE_DBPASS

admin_passwd: ADMIN_PASS
region_name: RegionOne

glance_keystone_user: glance
glance_keystone_passwd: GLANCE_PASS

nova_keystone_user: nova
nova_keystone_passwd: NOVA_PASS

neutron_keystone_user: neutron
neutron_keystone_passwd: NEUTRON_PASS

cinder_keystone_user: cinder
cinder_keystone_passwd: CINDER_PASS